import type { NextPage } from 'next'
import Head from 'next/head'
import { FormEvent } from 'react'
import styles from '../styles/Home.module.css'
import { sendRequest } from './service/request'

const Home: NextPage = () => {
  const handleSubmit = (event: FormEvent) => {
    event.preventDefault()

    sendRequest('api/help-desk', {})
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit}>
        <input type="text" name="name" id="name" />

        <button type="submit">Submit</button>
      </form>
    </div>
  )
}

export default Home
